### ISSUE TITLE
Extend Ladder Thresholds to be Build-Centric.

### ISSUE THREAD

**Issue by Kraust** [STOCD/OSCR-server#53]
e.g.

```
threshold:
   [0]: 
     - build: torps
     - value: 2000000
   [1]: 
     - build: dew
     - value: 5000000
```
